apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
 index.html: |
    <html>
        <body>
                <h1>Hello from SCGC Assignment!</h1>
                <h3>Miulescu Cristina-Maria, SCPD</h3>
        </body>
    </html>
