apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen       8080;
      server_name  nginx;


      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      location /metrics {
        stub_status;
        allow 1.1.1.1;
      }
    }
