apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      name: "html"
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088
      name: "metrics"
