apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-conf
data:
  default.conf: |
    server {
      listen       80;
      server_name  promexporter;


      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
