apiVersion: v1
kind: Service
metadata:
  name: promexporter
spec:
  type: NodePort
  selector:
    app: promexporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
      nodePort: 30081
      name: "html"
