apiVersion: apps/v1
kind: Deployment
metadata:
  name: promexporter
  labels:
    app: promexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promexporter
  template:
    metadata:
      labels:
        app: promexporter
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: prom-conf-vol
          mountPath: "/etc/nginx/conf.d/default.conf"
          subPath: "default.conf"
      - name: promexporter-container
        image: nginx/nginx-prometheus-exporter:0.8.0
        args: ["-nginx.scrape-uri", "http://nginx:8080/metrics"]
        ports:
        - containerPort: 9113
      volumes:
      - name: prom-conf-vol
        configMap:
          name: prom-conf
          items:
          - key: "default.conf"
            path: "default.conf"
